name: Feature request 🧭
description: Suggest an idea for this project. **Do not use this template to report bugs or ask questions.**
labels: "feature_request"
body:
  - type: markdown
    attributes:
      value: |
        # Welcome 👋

        Thanks for taking the time to fill out this feature request module.

        Please fill out each section below. This info allows Stereolabs developers to correctly evaluate your request.

        :warning: **Please use this template only to propose new features related to this repository** :warning:
        
        If you have a problem with a device, a ZED SDK tool, a bug to report, or *generic questions* to ask please do not open an issue on GitHub, but instead start a thread in the [StereoLabs Community Forum](https://community.stereolabs.com/).

        Useful Links:
        - Documentation: https://docs.stereolabs.com/
        - Stereolabs support: https://support.stereolabs.com/hc
        - StereoLabs Community Forum: https://community.stereolabs.com/
        
  - type: checkboxes
    attributes:
      label: Preliminary Checks
      description: Please make sure that you verify each checkbox and follow the instructions for them.
      options:
        - label: "This issue is not a duplicate. Before opening a new issue, please search existing issues."
          required: true
        - label: "This issue is not a question, bug report, or anything other than a feature request directly related to this project."
          required: true
  - type: textarea
    attributes:
      label: Proposal
      description: "What would you like to have as a new feature?"
      placeholder: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use-Case
      description: "How would this help you?"
      placeholder: "Tell us more what you'd like to achieve."
    validations:
      required: false
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: "Let us know if you have anything else to share"
